### ISSUE TITLE
Semester 1 last week push

### ISSUE THREAD

**Issue by ttunca** [gw-sd-2016/EcoFriendly#3]
This week i worked on data collection so i can later determine what kind of transportation the user is taking during their day. Because I hit some problems that i explained last class, i thought a great solution to my problem was making a mysql data base that tracked all the data collected during the users trips. This way i can find out what kind of transportation is used by looking back at the database during a certain time or location. for example if the first entry of the database said the person was in a certain location and then the second entry of the database had a location that was way too far for the person to walk to, then the application will know the user is on a moving vehicle. Location is not the only data i will collect. For more accuracy i will be using many censors like the accelerometer (to see if the user is actually moving). you will find most of these additions in the LocationHistoryDatabase and TripMonitor classes.

**Comment by twood02** [comment]
@ttunca @poorvi-vora

Tom, rather than creating a new folder for each of your commits, you should just be overwriting your previous files.  The beauty of git is that it will automatically retain your older versions, so as long as you have been committing and pushing your code you will never lose anything.

Over the break you should work on cleaning up your repository so it just has one version of your code.  You can still use folders for different components, but not for different versions of the same files.

**Comment by ttunca** [comment]
Hey professor,I will try and get a better understanding on github and clean it up over the break. I'm sorry it's a little messy, this was the first time I used github.Thank you for your comments,Tom Tunca <div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Tim Wood notifications@github.com </div><div>Date: 12/7/2015  12:03 PM  (GMT-05:00) </div><div>To: gw-sd-2016/EcoFriendly EcoFriendly@noreply.github.com </div><div>Cc: ttunca tomtunca@hotmail.com </div><div>Subject: Re: [EcoFriendly] Semester 1 last week push (#3) </div><div>
</div>
@ttunca @poorvi-vora

Tom, rather than creating a new folder for each of your commits, you should just be overwriting your previous files.  The beauty of git is that it will automatically retain your older versions, so as long as you have been committing and pushing your code you will never lose anything.

Over the break you should work on cleaning up your repository so it just has one version of your code.  You can still use folders for different components, but not for different versions of the same files.

---

**Comment by twood02** [comment]
sounds good!  (We'd rather have you figure out how to fix a messy repo now than once you start work!)
